name: ci build Pipeline
on: 
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v4
      - name: Install node version
        uses: actions/setup-node@v7
        with:
          node-version: 24
      - name: Install dependencies
        run: npm install
      - name: Lint the code
        run: |
          echo "Linting the code"
          npm run lint

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v4
      - name: Install node version
        uses: actions/setup-node@v7
        with:
          node-version: 24
      - name: Install dependencies
        run: npm install
      - name: test the code
        run: |
          echo "Testing the code"
          npm run test
  
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v4
      - name: Install node version
        uses: actions/setup-node@v7
        with:
          node-version: 24
      - name: Install dependencies
        run: npm install
      - name: build the code
        run: |
          echo "Building the code"
          npm run build
  